# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'dolphinconnection'
    subscriptionId: '6cf4c725-2dfa-4bb2-bb64-bd5b45f6a514'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dolphinpiperg'
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/weiliu2/weiliu2testpro/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName  dolpipe'
    deploymentMode: 'Incremental'
    deploymentName: 'dolphinpipelinedep'